version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:      
      - testing_net
    healthcheck:        
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s        
      timeout: 5s        
      retries: 10
    logging:
      driver: none

  
  receiver:
    container_name: receiver
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=receiver
      - PORT=12345
      - NAME_STATIONS_QUEUE=joiner_stations_q
      - NAME_WEATHER_QUEUE=joiner_weather_q
      - NAME_TRIPS_QUEUES=['join_trip_weather_q', 'join_trip_stations_q']
      - NAME_EM_QUEUE=eof_manager_joiners_q
    image: receiver:latest
    ports:
      - 12345:12345
      - 12346:12346
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  
  joiner_stations:
    container_name: joiner_stations
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - NAME_RECV_QUEUE=joiner_stations_q
      - NAME_TRIPS_QUEUE=join_trip_stations_q
      - NAME_EM_QUEUE=eof_manager_joiners_q
      - NAME_NEXT_STAGE_QUEUE=filter_joined_stations_q
    image: joiner_stations:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  
  joiner_weather:
    container_name: joiner_weather
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - NAME_RECV_QUEUE=joiner_weather_q
      - NAME_TRIPS_QUEUE=join_trip_weather_q
      - NAME_EM_QUEUE=eof_manager_joiners_q
      - NAME_NEXT_STAGE_QUEUE=filter_joined_weather_q
    image: joiner_weather:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  
  filter_pretoc_1:
    container_name: filter_pretoc_1
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: filter_pretoc:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  filter_pretoc_2:
    container_name: filter_pretoc_2
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: filter_pretoc:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  
  filter_year_1:
    container_name: filter_year_1
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: filter_year:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  
  groupby_query1:
    container_name: groupby_query1
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: groupby_query1:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  
  applier_query1_1:
    container_name: applier_query1_1
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: applier_query1:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


  eof_manager_joiners:
    container_name: eof_manager_joiners
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: eof_manager_joiners:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    
  
  eof_manager_filters:
    container_name: eof_manager_filters
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SIZE_WORKERS=[2, 1]
    image: eof_manager_filters:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  
  eof_manager_groupby:
    container_name: eof_manager_groupby
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: eof_manager_groupby:latest
    networks:      
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy


networks:
  testing_net:
    driver: bridge
