version: '3'
name: tp1
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  receiver:
    container_name: receiver
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: receiver:latest
    depends_on:
      - rabbitmq

  stations_handler:
    container_name: stations_handler
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: stations_handler:latest
    depends_on:
      - rabbitmq
      - em_handlers

  em_handlers:
    container_name: em_handlers
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: em_handlers:latest
    depends_on:
      - rabbitmq

  filter_trips:
    container_name: filter_trips
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: filter_trips:latest
    depends_on:
      - rabbitmq
      - em_filters

  filter_trips_stations:
    container_name: filter_trips_stations
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: filter_trips_stations:latest
    depends_on:
      - rabbitmq
      - em_filters

  em_filters:
    container_name: em_filters
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: em_filters:latest
    depends_on:
      - rabbitmq

  applier_2:
    container_name: applier_2
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: applier_2:latest
    depends_on:
      - rabbitmq
      - em_query2

  groupby_2:
    container_name: groupby_2
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: groupby_2:latest
    depends_on:
      - rabbitmq
      - em_query2

  em_query2:
    container_name: em_query2
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: em_query2:latest
    depends_on:
      - rabbitmq
