version: '3.9'
name: tp1-client
services:
  client:
    container_name: client
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: client:latest
    depends_on:
      - receiver
    networks:
      - bike-riders

networks:
  bike-riders:

