version: '3'
name: tp1
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      driver: none

  receiver:
    container_name: receiver
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=receiver
      - PORT_STATIC=12345
      - STATIONS_QUEUE=stations_queue
      - WEATHER_QUEUE=weather_queue
      - PORT_TRIPS=12346
      - TRIPS_QUEUE=trips_queue
      - JOIN_TRIPS_STATIONS_QUEUE=join_trip_station_queue
      - JOIN_TRIPS_WEATHER_QUEUE=join_trip_weather_queue
      - EM_QUEUE=eof_handler_queue
    image: receiver:latest
    ports:
      - 12345:12345
      - 12346:12346
    depends_on:
      - rabbitmq

  client:
    container_name: client
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=receiver
      - PORT_STATIC=12345
      - PORT_TRIPS=12346
      - STATIONS_QUEUE=stations_queue
    image: client:latest
    depends_on:
      - receiver

  stations_handler:
    container_name: stations_handler
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: stations_handler:latest
    depends_on:
      - rabbitmq
      - em_joiners

  weather_handler:
    container_name: weather_handler
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: weather_handler:latest
    depends_on:
      - rabbitmq
      - em_joiners

  em_joiners:
    container_name: em_joiners
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: em_joiners:latest
    depends_on:
      - rabbitmq

  filter_trips_1:
    container_name: filter_trips_1
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: filter_trips:latest
    depends_on:
      - rabbitmq
      - em_filters

  filter_trips_stations_1:
    container_name: filter_trips_stations_1
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: filter_trips_stations:latest
    depends_on:
      - rabbitmq
      - em_filters

  filter_trips_stations_2:
    container_name: filter_trips_stations_2
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: filter_trips_stations:latest
    depends_on:
      - rabbitmq
      - em_filters

  filter_trips_weather_1:
    container_name: filter_trips_weather_1
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: filter_trips_weather:latest
    depends_on:
      - rabbitmq
      - em_filters

  em_filters:
    container_name: em_filters
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: em_filters:latest
    depends_on:
      - rabbitmq

  groupby_1:
    container_name: groupby_1
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: groupby_1:latest
    depends_on:
      - rabbitmq
      - em_groupby

  groupby_2:
    container_name: groupby_2
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: groupby_2:latest
    depends_on:
      - rabbitmq
      - em_groupby

  groupby_3:
    container_name: groupby_3
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: groupby_3:latest
    depends_on:
      - rabbitmq
      - em_groupby

  em_groupby:
    container_name: em_groupby
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: em_groupby:latest
    depends_on:
      - rabbitmq

  applier_1_1:
    container_name: applier_1_1
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: applier_1:latest
    depends_on:
      - rabbitmq
      - em_applier

  applier_2_1:
    container_name: applier_2_1
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: applier_2:latest
    depends_on:
      - rabbitmq
      - em_applier

  applier_2_2:
    container_name: applier_2_2
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: applier_2:latest
    depends_on:
      - rabbitmq
      - em_applier

  applier_3_1:
    container_name: applier_3_1
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: applier_3:latest
    depends_on:
      - rabbitmq
      - em_applier

  em_applier:
    container_name: em_applier
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: em_applier:latest
    depends_on:
      - rabbitmq

  query_state_verifier:
    container_name: query_state_verifier
    entrypoint: python3 /main.py
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    image: query_state_verifier:latest
    depends_on:
      - rabbitmq
