version: '3.9'
name: tp1
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
      - 5672:5672

  receiver:
    container_name: receiver
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: receiver:latest
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    volumes:
      - ./common:/common

  stations_handler:
    container_name: stations_handler
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: stations_handler:latest
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    volumes:
      - ./common:/common

